<script setup lang="ts">
const props = defineProps<{ open: boolean; branding: Record<string, any>; settings: Record<string, any> }>()
const emit = defineEmits<{ close: []; saveBranding:[value:Record<string,any>]; reset: [] }>()
const name = ref(''); const tagline = ref(''); const dialog = ref<HTMLElement>()
const confirm = (message: string) => globalThis.confirm(message)
watch(() => props.open, (v) => { if(v){ name.value=props.branding?.appName || props.branding?.app_name || 'LensFlow Watermark Pro'; tagline.value=props.branding?.tagline || 'Sistem Watermark Otomatis Event & Studio'; nextTick(() => dialog.value?.focus()) } })
function key(e: KeyboardEvent) { if(e.key==='Escape') emit('close') }
</script>
<template><Teleport to="body"><Transition name="modal"><div v-if="open" class="modal-overlay" @mousedown.self="emit('close')" @keydown="key"><section ref="dialog" class="modal" role="dialog" aria-modal="true" aria-labelledby="settings-title" tabindex="-1"><header><div><h2 id="settings-title">Pengaturan Aplikasi</h2><p>Sesuaikan identitas LensFlow di workstation ini.</p></div><button class="btn btn-icon btn-ghost" aria-label="Tutup pengaturan" @click="emit('close')"><AppIcon name="close" /></button></header><div class="modal-body"><div class="settings-section"><h3>Nama & Branding</h3><div class="field-group"><label for="app-name">Nama utama aplikasi / studio</label><input id="app-name" v-model="name" maxlength="60"></div><div class="field-group"><label for="tagline">Subjudul / tagline</label><input id="tagline" v-model="tagline" maxlength="90"></div></div><div class="settings-section"><h3>Tentang & Privasi</h3><div class="privacy-panel"><strong>Pemrosesan lokal, tanpa AI</strong><p>Foto event tidak diunggah. Hanya konfigurasi atau metadata yang dapat disinkronkan jika API cloud tersedia.</p></div><dl class="about-list"><div><dt>Versi</dt><dd>1.0.0</dd></div><div><dt>Akses</dt><dd>Langsung, tanpa akun</dd></div></dl></div><button class="reset-link" @click="confirm('Reset seluruh pengaturan ke default?') && emit('reset')">Reset seluruh pengaturan</button></div><footer><button class="btn btn-secondary" @click="emit('close')">Batal</button><button class="btn btn-primary" @click="emit('saveBranding', { appName:name.trim(), app_name:name.trim(), tagline:tagline.trim() }); emit('close')">Simpan Pengaturan</button></footer></section></div></Transition></Teleport></template>
